In [57]:

import pandas as pd
import numpy as np

# Load the CSV file
df = pd.read_csv("239ac3d0-f08d-40d0-b03c-9b7a426a62d5.csv")

# Display the first 5 rows
df.head()

,COMM_NAME,COMM_CODE,COMM_WT,INDX042012,INDX052012,INDX062012,INDX072012,INDX082012,INDX092012,INDX102012,...,INDX012023,INDX022023,INDX032023,INDX042023,INDX052023,INDX062023,INDX072023,INDX082023,INDX092023,INDX102023
0,Bajra,1101010104,0.08637,107.7,109.3,107.0,113.9,120.7,121.7,114.8,...,224.1,219.6,225.1,229.6,229.4,226.7,226.9,225.9,225.7,231.5
1,Moong,1101010203,0.07088,96.3,96.0,96.6,103.6,108.7,108.4,112.2,...,167.7,167.8,172.8,180.8,178.6,184.8,188.7,189.4,199.7,205.6
2,Masur,1101010204,0.05299,102.5,107.4,109.7,115.2,119.2,119.0,118.6,...,199.0,196.3,194.6,192.1,188.1,187.7,186.6,186.9,192.6,189.5
3,Peas/Chawali,1101010206,0.02444,113.2,123.1,134.3,147.4,143.3,153.8,146.6,...,160.4,160.2,166.9,195.5,199.5,196.0,215.9,219.8,227.4,237.6
4,Cauliflower,1101020108,0.16697,119.1,0.0,0.0,0.0,0.0,134.6,129.4,...,161.1,148.4,163.5,176.9,0.0,0.0,0.0,0.0,230.3,244.6

In [5]:
print(df.shape)

(869, 142)

In [8]:
print(df.columns.tolist())

['COMM_NAME', 'COMM_CODE', 'COMM_WT', 'INDX042012', 'INDX052012', 'INDX062012', 'INDX072012', 'INDX082012', 'INDX092012', 'INDX102012', 'INDX112012', 'INDX122012', 'INDX012013', 'INDX022013', 'INDX032013', 'INDX042013', 'INDX052013', 'INDX062013', 'INDX072013', 'INDX082013', 'INDX092013', 'INDX102013', 'INDX112013', 'INDX122013', 'INDX012014', 'INDX022014', 'INDX032014', 'INDX042014', 'INDX052014', 'INDX062014', 'INDX072014', 'INDX082014', 'INDX092014', 'INDX102014', 'INDX112014', 'INDX122014', 'INDX012015', 'INDX022015', 'INDX032015', 'INDX042015', 'INDX052015', 'INDX062015', 'INDX072015', 'INDX082015', 'INDX092015', 'INDX102015', 'INDX112015', 'INDX122015', 'INDX012016', 'INDX022016', 'INDX032016', 'INDX042016', 'INDX052016', 'INDX062016', 'INDX072016', 'INDX082016', 'INDX092016', 'INDX102016', 'INDX112016', 'INDX122016', 'INDX012017', 'INDX022017', 'INDX032017', 'INDX042017', 'INDX052017', 'INDX062017', 'INDX072017', 'INDX082017', 'INDX092017', 'INDX102017', 'INDX112017', 'INDX122017', 'INDX012018', 'INDX022018', 'INDX032018', 'INDX042018', 'INDX052018', 'INDX062018', 'INDX072018', 'INDX082018', 'INDX092018', 'INDX102018', 'INDX112018', 'INDX122018', 'INDX012019', 'INDX022019', 'INDX032019', 'INDX042019', 'INDX052019', 'INDX062019', 'INDX072019', 'INDX082019', 'INDX092019', 'INDX102019', 'INDX112019', 'INDX122019', 'INDX012020', 'INDX022020', 'INDX032020', 'INDX042020', 'INDX052020', 'INDX062020', 'INDX072020', 'INDX082020', 'INDX092020', 'INDX102020', 'INDX112020', 'INDX122020', 'INDX012021', 'INDX022021', 'INDX032021', 'INDX042021', 'INDX052021', 'INDX062021', 'INDX072021', 'INDX082021', 'INDX092021', 'INDX102021', 'INDX112021', 'INDX122021', 'INDX012022', 'INDX022022', 'INDX032022', 'INDX042022', 'INDX052022', 'INDX062022', 'INDX072022', 'INDX082022', 'INDX092022', 'INDX102022', 'INDX112022', 'INDX122022', 'INDX012023', 'INDX022023', 'INDX032023', 'INDX042023', 'INDX052023', 'INDX062023', 'INDX072023', 'INDX082023', 'INDX092023', 'INDX102023']

In [55]:
df1 = pd.read_csv(r"C:\Users\sanga\BharatPulse\BharatPulse\outputs\bharatpulse_cleaned.csv")
display(df.columns)

Index(['COMM_NAME', 'COMM_CODE', 'COMM_WT', 'INDX042012', 'INDX052012',
       'INDX062012', 'INDX072012', 'INDX082012', 'INDX092012', 'INDX102012',
       ...
       'INDX012023', 'INDX022023', 'INDX032023', 'INDX042023', 'INDX052023',
       'INDX062023', 'INDX072023', 'INDX082023', 'INDX092023', 'INDX102023'],
      dtype='str', length=142)

In [46]:
import os

os.getcwd()

'C:\\Users\\sanga\\BharatPulse\\BharatPulse'

In [47]:
os.listdir()

['.ipynb_checkpoints',
 '239ac3d0-f08d-40d0-b03c-9b7a426a62d5.csv',
 'data cleaning.ipynb',
 'outputs']

In [48]:
import os

for root, dirs, files in os.walk(os.getcwd()):
    if "bharatpulse_cleaned.csv" in files:
        print(os.path.join(root, "bharatpulse_cleaned.csv"))

C:\Users\sanga\BharatPulse\BharatPulse\outputs\bharatpulse_cleaned.csv

In [58]:
df.head()

,COMM_NAME,COMM_CODE,COMM_WT,INDX042012,INDX052012,INDX062012,INDX072012,INDX082012,INDX092012,INDX102012,...,INDX012023,INDX022023,INDX032023,INDX042023,INDX052023,INDX062023,INDX072023,INDX082023,INDX092023,INDX102023
0,Bajra,1101010104,0.08637,107.7,109.3,107.0,113.9,120.7,121.7,114.8,...,224.1,219.6,225.1,229.6,229.4,226.7,226.9,225.9,225.7,231.5
1,Moong,1101010203,0.07088,96.3,96.0,96.6,103.6,108.7,108.4,112.2,...,167.7,167.8,172.8,180.8,178.6,184.8,188.7,189.4,199.7,205.6
2,Masur,1101010204,0.05299,102.5,107.4,109.7,115.2,119.2,119.0,118.6,...,199.0,196.3,194.6,192.1,188.1,187.7,186.6,186.9,192.6,189.5
3,Peas/Chawali,1101010206,0.02444,113.2,123.1,134.3,147.4,143.3,153.8,146.6,...,160.4,160.2,166.9,195.5,199.5,196.0,215.9,219.8,227.4,237.6
4,Cauliflower,1101020108,0.16697,119.1,0.0,0.0,0.0,0.0,134.6,129.4,...,161.1,148.4,163.5,176.9,0.0,0.0,0.0,0.0,230.3,244.6

In [60]:
print(df.shape)

(869, 142)

In [61]:
df.describe()

,COMM_CODE,COMM_WT,INDX042012,INDX052012,INDX062012,INDX072012,INDX082012,INDX092012,INDX102012,INDX112012,...,INDX012023,INDX022023,INDX032023,INDX042023,INDX052023,INDX062023,INDX072023,INDX082023,INDX092023,INDX102023
count,8.690000e+02,868.000000,869.000000,869.000000,869.000000,869.000000,869.000000,869.000000,869.000000,869.000000,...,869.000000,869.000000,869.000000,869.000000,869.000000,869.000000,869.000000,869.000000,869.000000,869.000000
mean,1.275946e+09,0.568565,103.852589,103.687572,104.550173,105.507480,105.660069,105.875144,106.068585,106.429229,...,148.453395,148.529114,148.270771,148.600690,147.107940,147.203797,149.118067,149.047641,148.685501,149.679171
std,8.216739e+07,4.219486,10.765165,12.845610,12.422794,13.529574,13.975477,13.797784,12.792478,12.121561,...,43.821126,42.668332,40.470594,40.000942,41.081976,42.103654,55.016715,51.542506,46.186661,46.654536
min,1.000000e+09,0.000020,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.301100e+09,0.022367,100.500000,100.700000,101.500000,101.600000,101.800000,102.100000,102.000000,101.700000,...,124.300000,124.800000,125.200000,126.000000,125.000000,124.200000,124.400000,124.800000,125.000000,125.200000
50%,1.310070e+09,0.075520,103.100000,103.700000,104.100000,104.700000,104.900000,105.200000,105.300000,105.300000,...,140.600000,140.900000,140.900000,141.000000,140.300000,139.300000,139.400000,139.800000,140.500000,140.400000
75%,1.316040e+09,0.241160,106.600000,106.800000,107.300000,108.500000,109.600000,109.500000,109.500000,109.600000,...,163.100000,162.900000,162.400000,162.400000,161.200000,160.400000,161.500000,160.800000,162.800000,163.600000
max,2.000000e+09,100.000000,245.200000,253.400000,216.400000,194.600000,198.000000,189.400000,181.200000,185.200000,...,640.500000,558.000000,472.700000,400.500000,433.100000,536.200000,1043.600000,813.900000,548.200000,497.400000

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 869 entries, 0 to 868
Columns: 142 entries, COMM_NAME to INDX102023
dtypes: float64(140), int64(1), str(1)
memory usage: 964.2 KB